# Generated by Django 3.1 on 2020-10-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust', models.CharField(max_length=100)),
                ('sauce', models.CharField(max_length=100)),
                ('cheese', models.CharField(max_length=100)),
                ('topping1', models.CharField(max_length=100)),
                ('topping2', models.CharField(blank=True, default='', max_length=100)),
                ('toasted', models.BooleanField(null=True)),
            ],
        ),
    ]
