# Generated by Django 3.1 on 2020-10-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_pizza_pizza_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(help_text='What drink would you like?', max_length=500)),
                ('drink_size', models.CharField(help_text='What size?', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(help_text='Please choose your crust preference', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(help_text='Type your name in here', max_length=500),
        ),
    ]
