# Generated by Django 3.1 on 2020-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=10000)),
                ('pub_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
