# Generated by Django 3.1 on 2020-09-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
