# Generated by Django 3.1 on 2020-09-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='speciallink',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
