# Generated by Django 3.1 on 2020-09-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_post_speciallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='speciallink',
            new_name='website',
        ),
    ]
