# Generated by Django 3.1 on 2020-09-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
