# Generated by Django 3.1 on 2020-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_auto_20200923_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='', max_length=100),
        ),
    ]
