# Generated by Django 3.1 on 2020-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('0', 'Community'), ('1', 'Environment'), ('2', 'Food/ Agriculture'), ('3', 'Materials and Production'), ('4', 'Social Good')], default='', max_length=1),
        ),
    ]
