# Generated by Django 3.1 on 2020-09-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0012_post_featured_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image_link',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
