# Generated by Django 3.1 on 2020-09-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_auto_20200923_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
