# Generated by Django 3.1 on 2020-09-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0015_auto_20200923_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
